extends Node

var HP_PLAYER = 100.0
var SPEED_PLAYER = 200.00
var DASH_SPEED = 3000.00
var CURRENT_WAVE_LEVEL = 1
var WAVE_BOSS_LEVEL = 5
var TOTAL_MINIMUM_MOB = 10
var TOTAL_MOB_ONSTAGE = 0
var TOTAL_DEFEATED_MONSTER = 0
var TOTAL_SCORE = 0
